name: Test Secrets
on: workflow_dispatch
jobs:
  build:
    runs-on: windows-latest
    env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TEST_SECRET: ${{ secrets.TEST_SECRET }}
    steps:
    - name: Test
      run: Write-Output $env:TEST_SECRET
